server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/whatsapp
    password: manash@12345@
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true